"""add auto_minutes to meetings

Revision ID: 55476b600c52
Revises: 2474d66cae2b
Create Date: 2026-04-07 13:47:16.242953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55476b600c52'
down_revision: Union[str, None] = '2474d66cae2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('auto_minutes', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'auto_minutes')
    # ### end Alembic commands ###
